/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.UserDAO;
import java.text.SimpleDateFormat;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Admin
 */
public class registerUser extends javax.swing.JFrame {

    /**
     * Creates new form registerUser
     */
    public registerUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtRole = new javax.swing.JLabel();
        jRadioButton_Male = new javax.swing.JRadioButton();
        jRadioButton_Female = new javax.swing.JRadioButton();
        txtBod = new com.toedter.calendar.JDateChooser();
        txtPassword = new javax.swing.JPasswordField();
        showPass = new javax.swing.JCheckBox();
        back_loginUser = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 150));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 255, 204));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Full Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Phone :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 109, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Gender :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 108, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Bod :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 109, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Role :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 109, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Username :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 109, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Password :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 109, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Email :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 109, -1));

        btnSave.setBackground(new java.awt.Color(204, 204, 255));
        btnSave.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 0, 0));
        btnSave.setText("Sign Up");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 130, 40));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 187, -1));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 187, -1));

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 187, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 187, -1));

        txtRole.setFont(new java.awt.Font("PT Serif Caption", 1, 12)); // NOI18N
        txtRole.setForeground(new java.awt.Color(0, 0, 0));
        txtRole.setText("Player");
        getContentPane().add(txtRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 60, 30));

        jRadioButton_Male.setBackground(new java.awt.Color(153, 153, 153));
        jRadioButton_Male.setFont(new java.awt.Font("PT Serif Caption", 1, 12)); // NOI18N
        jRadioButton_Male.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton_Male.setText("Male");
        getContentPane().add(jRadioButton_Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 70, -1));

        jRadioButton_Female.setBackground(new java.awt.Color(153, 153, 153));
        jRadioButton_Female.setFont(new java.awt.Font("PT Serif Caption", 1, 12)); // NOI18N
        jRadioButton_Female.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton_Female.setText("Female");
        getContentPane().add(jRadioButton_Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 80, -1));
        getContentPane().add(txtBod, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 180, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 190, -1));

        showPass.setBackground(new java.awt.Color(153, 153, 153));
        showPass.setFont(new java.awt.Font("PT Serif Caption", 1, 12)); // NOI18N
        showPass.setForeground(new java.awt.Color(0, 0, 0));
        showPass.setText("show password");
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });
        getContentPane().add(showPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 130, -1));

        back_loginUser.setBackground(new java.awt.Color(204, 204, 204));
        back_loginUser.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        back_loginUser.setForeground(new java.awt.Color(0, 0, 0));
        back_loginUser.setText("Back");
        back_loginUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_loginUserMouseClicked(evt);
            }
        });
        back_loginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_loginUserActionPerformed(evt);
            }
        });
        getContentPane().add(back_loginUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("PT Sans Caption", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("REGISTER");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 190, 36));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fofm.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 560));

        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        String name = txtName.getText();
        String phone = txtPhone.getText();
        String gender = "Male";
        if (jRadioButton_Female.isSelected()) {
            gender = "Female";
        }
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String bod = "12-02-2024";
        String role = (String) txtRole.getText();
        String username = txtUsername.getText();
        String PASSWORD = txtPassword.getText();
        String email = txtEmail.getText();

        if (name.isEmpty() || phone.isEmpty() || username.isEmpty() || PASSWORD.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill the information.");
            return;
        }
        if (!name.matches(".*\\d.*") && name.length() <= 40) {
            // Kiểm tra mẫu cho điện thoại dưới 10 số không có chữ cái
            if (phone.matches("\\d{3}-\\d{3}-\\d{3,4}")) {
                // Kiểm tra mẫu cho tên người dùng dưới 10 ký tự
                if (username.length() <= 20) {
                    // Kiểm tra mẫu chọn mật khẩu dưới 20 ký tự
                    if (PASSWORD.length() <= 20) {
                        // Kiểm tra mẫu chọn email dưới 15 ký tự, bắt buộc có @.com
                        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@gmail\\.com$";

                        if (email.matches(emailRegex) && email.length() <= 30) {
                            // Nếu tất cả điều kiện đều thỏa mãn, tiến hành thêm vào cơ sở dữ liệu
                            UserDAO res = new UserDAO();
                            res.insertPlayer(name, phone, gender, bod, role, username, PASSWORD, email);
                            this.dispose();

                            return;
                        } else {
                            JOptionPane.showMessageDialog(this, "Invalid Email, @gmail.com.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Invalid password.");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid username.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid phone number, xxx-xxx-xxx(x)  .");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid name.");
        }

//        UserDAO res = new UserDAO();
//        res.insertPlayer(name, phone, gender, bod, role, username, PASSWORD, email);
//        this.dispose(); 
//        new UserLogin().setVisible(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void back_loginUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_loginUserActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UserLogin().setVisible(true);
    }//GEN-LAST:event_back_loginUserActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void back_loginUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_loginUserMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new UserLogin().setVisible(true);
    }//GEN-LAST:event_back_loginUserMouseClicked

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
        // TODO add your handling code here:
        if (showPass.isSelected()) {
            txtPassword.setEchoChar((char) 0);
        } else {
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_showPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_loginUser;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton_Female;
    private javax.swing.JRadioButton jRadioButton_Male;
    private javax.swing.JCheckBox showPass;
    private com.toedter.calendar.JDateChooser txtBod;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JLabel txtRole;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
