/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.Result;
import dao.ResultDAO;
import dao.User;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author minh
 */
public class ViewResult extends javax.swing.JFrame {

    int index = 0;
    private final Result result;
    ArrayList<User> dsUser = new ArrayList();

    public ViewResult(Result result) {
        initComponents();
        this.result = result;
        inforUser();
    }

    private void inforUser() {
        dsUser = dao.UserDAO.getByID(result.userID);
        LabelName.setText(dsUser.get(index).name);
        labelID.setText(String.valueOf(result.userID));
        labelMark.setText(String.valueOf(result.score));
        labelDuration.setText(result.duration);
        labelTopic.setText(result.topic);
        labelLevel.setText(String.valueOf(result.level));
        labelDate.setText(result.date);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ViewAllBTN = new javax.swing.JButton();
        labelID = new javax.swing.JLabel();
        labelDuration = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        labelName1 = new javax.swing.JLabel();
        labelName2 = new javax.swing.JLabel();
        labelDuration1 = new javax.swing.JLabel();
        labelDuration2 = new javax.swing.JLabel();
        labelDuration3 = new javax.swing.JLabel();
        labelName3 = new javax.swing.JLabel();
        labelMark = new javax.swing.JLabel();
        labelTopic = new javax.swing.JLabel();
        labelDuration4 = new javax.swing.JLabel();
        labelLevel = new javax.swing.JLabel();
        labelName4 = new javax.swing.JLabel();
        LabelName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(75, 75));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("PT Sans Caption", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/customers.png"))); // NOI18N
        jLabel2.setText("Result");

        ViewAllBTN.setBackground(new java.awt.Color(204, 204, 204));
        ViewAllBTN.setFont(new java.awt.Font("PT Sans Caption", 1, 14)); // NOI18N
        ViewAllBTN.setForeground(new java.awt.Color(0, 0, 0));
        ViewAllBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/customers.png"))); // NOI18N
        ViewAllBTN.setText("Result");
        ViewAllBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewAllBTNMouseClicked(evt);
            }
        });
        ViewAllBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllBTNActionPerformed(evt);
            }
        });

        labelID.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        labelID.setForeground(new java.awt.Color(255, 0, 0));
        labelID.setText("10");

        labelDuration.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        labelDuration.setForeground(new java.awt.Color(0, 0, 0));
        labelDuration.setText("12:31");

        labelDate.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        labelDate.setForeground(new java.awt.Color(0, 0, 0));
        labelDate.setText("LE DUC MINH");

        labelName1.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        labelName1.setForeground(new java.awt.Color(0, 0, 0));
        labelName1.setText("ID:");

        labelName2.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        labelName2.setForeground(new java.awt.Color(0, 0, 0));
        labelName2.setText("MARKS OBTAINED: ");

        labelDuration1.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        labelDuration1.setForeground(new java.awt.Color(0, 0, 0));
        labelDuration1.setText("DURATION:");

        labelDuration2.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        labelDuration2.setForeground(new java.awt.Color(0, 0, 0));
        labelDuration2.setText("DATE:");

        labelDuration3.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        labelDuration3.setForeground(new java.awt.Color(0, 0, 0));
        labelDuration3.setText("SUCCESSFULLY UPDATED!!");

        labelName3.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        labelName3.setForeground(new java.awt.Color(0, 0, 0));
        labelName3.setText("TOPIC:");

        labelMark.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        labelMark.setForeground(new java.awt.Color(0, 0, 0));
        labelMark.setText("10");

        labelTopic.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        labelTopic.setForeground(new java.awt.Color(0, 0, 0));
        labelTopic.setText("HTML");

        labelDuration4.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        labelDuration4.setForeground(new java.awt.Color(0, 0, 0));
        labelDuration4.setText("LEVEL:");

        labelLevel.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        labelLevel.setForeground(new java.awt.Color(0, 0, 0));
        labelLevel.setText("1");

        labelName4.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        labelName4.setForeground(new java.awt.Color(0, 0, 0));
        labelName4.setText("Name:");

        LabelName.setFont(new java.awt.Font("PT Sans Caption", 1, 20)); // NOI18N
        LabelName.setForeground(new java.awt.Color(0, 0, 0));
        LabelName.setText("10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelName2)
                            .addComponent(labelName3))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTopic)
                            .addComponent(labelMark)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelName1)
                        .addGap(18, 18, 18)
                        .addComponent(labelID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelName4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDuration1)
                            .addComponent(labelDuration2))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelDate)
                            .addComponent(labelDuration)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelDuration4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelLevel)))
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelDuration3)
                .addGap(211, 211, 211)
                .addComponent(ViewAllBTN)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(440, 440, 440))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName1)
                    .addComponent(labelID))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDuration)
                    .addComponent(labelDuration1)
                    .addComponent(labelName4)
                    .addComponent(LabelName))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName2)
                    .addComponent(labelMark)
                    .addComponent(labelDuration2)
                    .addComponent(labelDate))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelName3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDuration4)
                        .addComponent(labelTopic)
                        .addComponent(labelLevel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ViewAllBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDuration3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 93, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/index background.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewAllBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllBTNActionPerformed
        // TODO add your handling code here:

        this.dispose();
        new AllResult(dsUser.get(index).userID).setVisible(true);
    }//GEN-LAST:event_ViewAllBTNActionPerformed

    private void ViewAllBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewAllBTNMouseClicked

    }//GEN-LAST:event_ViewAllBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Result result = new Result();
                new ViewResult(result).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelName;
    private javax.swing.JButton ViewAllBTN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelDuration;
    private javax.swing.JLabel labelDuration1;
    private javax.swing.JLabel labelDuration2;
    private javax.swing.JLabel labelDuration3;
    private javax.swing.JLabel labelDuration4;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelLevel;
    private javax.swing.JLabel labelMark;
    private javax.swing.JLabel labelName1;
    private javax.swing.JLabel labelName2;
    private javax.swing.JLabel labelName3;
    private javax.swing.JLabel labelName4;
    private javax.swing.JLabel labelTopic;
    // End of variables declaration//GEN-END:variables
}
